Feat: FE - set checkbox required value based on sliders state
CLARIN-PL/doccano pull request #98
Opened 2023-04-08 16:16 UTC by artikandri

Features added with this PR:
- Ability to set Humor and Offensive checkboxes question required status by humor and offensive sliders value. The question required state will be set as true when at least one humor/offensive sliders is checked and the value > 0 
- Fixed a styling bug: I forgot to put the styling for the component inside the parent `{}`, hence if we opened the DynamicAnnotation project after the AffectiveAnnotation project, the styling may conflict with each other. I apologize for the inconvenience

What's changed: 
- `frontend/components/tasks/affectiveAnnotation/humor/HumorInput.vue`: moved the styling inside `.humor-input {}`
- `frontend/components/tasks/affectiveAnnotation/offensive/OffensiveInput.vue`: moved the styling inside `.offensive-input {}`
- `frontend/components/tasks/dynamicAnnotation/CheckboxInput.vue`: moved the styling inside `.checkbox-input {}`, disabled & transparent rules, minor styling
- `frontend/components/tasks/dynamicAnnotation/SliderInput.vue`: moved the styling inside `.slider-input {}`, disabled r& transparent rules  
- `frontend/pages/projects/_id/dynamic-annotation/index.vue`: set the dim required + disabled + transparent props value based on their type and their value

Screenshots: 
![image](https://user-images.githubusercontent.com/12537724/230731786-745fddb6-45b0-45d7-b86e-7e81f768374c.png)

2023-04-12 11:02 UTC, haanh764 requested changes
Hello, thank you so much for your work. However, I think I found 2 bugs related to the sliders in humor and offensive section, as in the recording below:
1. It's quite minor but after changing the value in these sliders, If I want to change it back to 0, I have to click to the 0 point (sliding it back to 0 position doesn't work). 
2. As you can see, when I change the value of 1st slider somehow the value of 2nd slider also changed and vice versa. 

https://user-images.githubusercontent.com/17596118/231438374-4af1e51b-b931-4df6-9b32-2f5488d7632e.mp4

2023-04-12 12:07 UTC, artikandri commented
Hello, thank you for finding the bug and sorry for the inconvenience. Both of the bugs were caused by me not handling the `change` event; I used the `click` event instead, but I forgot slider can be slided and `slide` event is not included in the `click` event. I have updated it to use the `change` event, can you check?

2023-04-13 09:52 UTC, haanh764 commented
> Hello, thank you for finding the bug and sorry for the inconvenience. Both of the bugs were caused by me not handling the `change` event; I used the `click` event instead, but I forgot slider can be slided and `slide` event is not included in the `click` event. I have updated it to use the `change` event, can you check?

Hello, thank yo

2023-04-13 09:56 UTC, haanh764 commented
> Hello, thank you for finding the bug and sorry for the inconvenience. Both of the bugs were caused by me not handling the `change` event; I used the `click` event instead, but I forgot slider can be slided and `slide` event is not included in the `click` event. I have updated it to use the `change` event, can you check?

Hello, thank you for very quick fix (the close and open above is due to the lagging for a moment in my PC, sorry :sweat_smile: ). The 2 bugs I mentioned above has been solved, thank you. However, I think there is still a bug with the humor section, the 1st slider `Bawi/śmieszny mnie` doesn't work as in the recording. I have checked database and I see it doesn't save value into table when I change that slider's value. Can you check it?


https://user-images.githubusercontent.com/17596118/231723726-a1433974-837e-4f18-b2e0-7486114e44de.mp4

2023-04-13 11:21 UTC, haanh764 approved these changes
Hello, so I think it's oke for now. I have checked it with new project creation with that dimension/slider. And everything works fine. So approved!

2023-05-08 04:04 UTC, merged